// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DetailRequest struct {
	UserId int64 `form:"userId"`
}

type DetailResponse struct {
	Username string `json:"username"`
	Gender   int64  `json:"gender"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message string `json:"message"`
}

type SignupRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Gender     int    `json:"gender, options=0|1|2,default=0"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
