// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SignupRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender, options=mal|female|secret,default=secret"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
