// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SearchRequest struct {
	OrderID string `form:"orderId"`
}

type SearchResponse struct {
	OrderID  string `json:"orderId"`
	Status   int    `json:"status"`
	Username string `json:"username"`
}
